### ISSUE TITLE
D[ Sqrt[1+x], x] gives RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by arnoudbuzing** [coffeemug/ts-wolfram#2]
This is very nice, but some functions give call stack errors (Maybe because it is not implemented?:

> D[ Sqrt[1+x], x]
RangeError: Maximum call stack size exceeded
    at evalSym (/Users/arnoudb/ts-wolfram/dist/ts-wolfram.cjs.development.js:888:31)
    at eval_ (/Users/arnoudb/ts-wolfram/dist/ts-wolfram.cjs.development.js:880:12)
    at evalForm (/Users/arnoudb/ts-wolfram/dist/ts-wolfram.cjs.development.js:896:15)
    at eval_ (/Users/arnoudb/ts-wolfram/dist/ts-wolfram.cjs.development.js:884:12)
    at matchPatternTest (/Users/arnoudb/ts-wolfram/dist/ts-wolfram.cjs.development.js:641:10)
    at match (/Users/arnoudb/ts-wolfram/dist/ts-wolfram.cjs.development.js:591:12)
    at matchForm (/Users/arnoudb/ts-wolfram/dist/ts-wolfram.cjs.development.js:607:10)
    at match (/Users/arnoudb/ts-wolfram/dist/ts-wolfram.cjs.development.js:594:33)
    at replace (/Users/arnoudb/ts-wolfram/dist/ts-wolfram.cjs.development.js:647:9)
    at replaceAll (/Users/arnoudb/ts-wolfram/dist/ts-wolfram.cjs.development.js:655:13)

**Comment by coffeemug** [comment]
Oh yes, a lot of stuff isn't implemented. I meant this project as a way to learn about how internals of Wolfram language work, not as a serious implementation. That said, it's fun to keep extending it :)

To get `Sqrt` working I'd need to implement `Rational`. That shouldn't be too hard, I'll see if I can carve out some time to do it after work.

**Comment by arnoudbuzing** [comment]
Do you plan on significantly extending this project? (I work for Wolfram Research and am interested in these sort of projects)

**Comment by coffeemug** [comment]
I can definitely see myself hacking on it-- for fun, to better understand the semantics of the Wolfram language, to try out ideas, etc. For example, I wanted to try out adding a type system/inferencing type checker to see what a statically typed Wolfram language might look like. But I'm not sure about "significantly" extending it. I don't see much public benefit in such an undertaking.

**Comment by arnoudbuzing** [comment]
Thanks for the feedback. I am going to close this issue, I mostly opened it to get a sense of your plans with this. I tried connecting on LinkedIn with you, but we have too many degrees of separation between us....

**Comment by coffeemug** [comment]
No problem, just added you on LinkedIn. Says pending.
